export interface DemoProduct {
  name: string;
  price: number;
  compareAtPrice?: number;
  categorySlug: string;
  occasionSlugs: string[];
  description: string;
  personalizable?: boolean;
  prepMinutes?: number;
}

export interface DemoBusiness {
  name: string;
  municipalitySlug: string;
  whatsapp: string;
  description: string;
  addressLine: string;
  prepMinutes: number;
  products: DemoProduct[];
}

/**
 * Catálogo de demostración — 10 negocios ficticios y 50+ productos (sección
 * 36 del spec). Todos marcados `isDemo` en el seed; nunca usar nombres de
 * negocios reales sin autorización.
 */
export const DEMO_BUSINESSES: DemoBusiness[] = [
  {
    name: "Rosas del Valle",
    municipalitySlug: "san-salvador",
    whatsapp: "+503 7000-0001",
    description: "Floristería especializada en arreglos frescos para toda ocasión. [DEMO]",
    addressLine: "Colonia Escalón, San Salvador",
    prepMinutes: 90,
    products: [
      {
        name: "Ramo Clásico de 12 Rosas Rojas",
        price: 28.99,
        categorySlug: "flores",
        occasionSlugs: ["aniversario", "te-amo"],
        description: "Doce rosas rojas frescas envueltas a mano con papel kraft y listón.",
      },
      {
        name: "Caja Romántica con Rosas y Chocolates",
        price: 34.99,
        compareAtPrice: 44.99,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["aniversario", "te-amo"],
        description: "Seis rosas, chocolates surtidos y una tarjeta personalizada en una caja elegante.",
        personalizable: true,
      },
      {
        name: "Girasoles Radiantes",
        price: 24.5,
        categorySlug: "flores",
        occasionSlugs: ["cumpleanos", "felicidades"],
        description: "Bouquet de girasoles frescos, ideal para alegrar el día de alguien.",
      },
      {
        name: "Rosas Blancas para Disculpas",
        price: 26,
        categorySlug: "flores",
        occasionSlugs: ["perdon"],
        description: "Un ramo de rosas blancas para decir lo que cuesta poner en palabras.",
      },
      {
        name: "Arreglo Floral Elegante",
        price: 39.99,
        categorySlug: "flores",
        occasionSlugs: ["graduacion", "felicidades"],
        description: "Arreglo mixto en base de cerámica, perfecto para graduaciones y logros.",
      },
      {
        name: "Rosa Individual con Tarjeta",
        price: 9.99,
        categorySlug: "flores",
        occasionSlugs: ["pense-en-vos"],
        description: "Una rosa roja con una tarjeta donde podés escribir tu propio mensaje.",
        personalizable: true,
      },
    ],
  },
  {
    name: "Choco Amor",
    municipalitySlug: "santa-tecla",
    whatsapp: "+503 7000-0002",
    description: "Chocolatería artesanal salvadoreña. [DEMO]",
    addressLine: "Paseo El Carmen, Santa Tecla",
    prepMinutes: 60,
    products: [
      {
        name: "Caja de Chocolates Belgas x12",
        price: 18.5,
        compareAtPrice: 24.99,
        categorySlug: "chocolates",
        occasionSlugs: ["te-amo", "aniversario"],
        description: "Selección de chocolates belgas rellenos, en caja de regalo.",
      },
      {
        name: "Fresas Cubiertas de Chocolate",
        price: 22,
        categorySlug: "chocolates",
        occasionSlugs: ["aniversario", "te-amo"],
        description: "Docena de fresas frescas bañadas en chocolate negro y blanco.",
      },
      {
        name: "Chocolate Artesanal con Mensaje",
        price: 15.99,
        categorySlug: "chocolates",
        occasionSlugs: ["pense-en-vos"],
        description: "Barra de chocolate artesanal grabada con el mensaje que elijas.",
        personalizable: true,
      },
      {
        name: "Combo Chocolate + Café Gourmet",
        price: 27,
        categorySlug: "chocolates",
        occasionSlugs: ["gracias"],
        description: "Chocolates surtidos junto a una bolsa de café gourmet salvadoreño.",
      },
      {
        name: "Trufas de Chocolate Surtidas",
        price: 16.75,
        categorySlug: "chocolates",
        occasionSlugs: ["felicidades"],
        description: "Dieciséis trufas artesanales en sabores variados.",
      },
      {
        name: "Chocolate Caliente Gourmet para Regalar",
        price: 12,
        categorySlug: "chocolates",
        occasionSlugs: ["solo-porque-si"],
        description: "Kit de chocolate caliente gourmet con marshmallows, listo para regalar.",
      },
    ],
  },
  {
    name: "Cajas con Cariño",
    municipalitySlug: "antiguo-cuscatlan",
    whatsapp: "+503 7000-0003",
    description: "Cajas de regalo curadas para cada ocasión. [DEMO]",
    addressLine: "Multiplaza, Antiguo Cuscatlán",
    prepMinutes: 120,
    products: [
      {
        name: 'Caja Sorpresa "Pensando en Vos"',
        price: 32,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["pense-en-vos"],
        description: "Snacks, una vela aromática y una nota escrita a mano.",
        personalizable: true,
      },
      {
        name: "Caja Spa en Casa",
        price: 45,
        compareAtPrice: 55,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["gracias", "felicidades"],
        description: "Mascarillas, sales de baño y velas para una tarde de relajación.",
      },
      {
        name: "Caja de Cumpleaños Deluxe",
        price: 38.5,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["cumpleanos"],
        description: "Globo, confeti, dulces y una tarjeta de cumpleaños.",
      },
      {
        name: 'Caja "Lo Siento" con Detalles',
        price: 29.99,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["perdon"],
        description: "Una combinación pensada para pedir disculpas con sinceridad.",
      },
      {
        name: "Caja Café + Postres",
        price: 24.99,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["gracias"],
        description: "Café de especialidad y mini postres horneados localmente.",
      },
      {
        name: "Caja Personalizada para Él",
        price: 36,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["aniversario"],
        description: "Snacks salados, una playera y un detalle a elección.",
        personalizable: true,
      },
    ],
  },
  {
    name: "Dulce Locura Pastelería",
    municipalitySlug: "san-salvador",
    whatsapp: "+503 7000-0004",
    description: "Pasteles y postres horneados por encargo. [DEMO]",
    addressLine: "Colonia San Benito, San Salvador",
    prepMinutes: 180,
    products: [
      {
        name: "Pastel de Chocolate Personalizado",
        price: 35,
        compareAtPrice: 42,
        categorySlug: "pasteles",
        occasionSlugs: ["cumpleanos"],
        description: "Pastel de chocolate húmedo con el mensaje que elijas en la cobertura.",
        personalizable: true,
      },
      {
        name: "Cupcakes Decorados (caja de 6)",
        price: 18,
        categorySlug: "postres",
        occasionSlugs: ["celebraciones"],
        description: "Seis cupcakes decorados a mano, sabores surtidos.",
      },
      {
        name: "Pastel Red Velvet",
        price: 32,
        categorySlug: "pasteles",
        occasionSlugs: ["cumpleanos", "aniversario"],
        description: "Clásico red velvet con betún de queso crema.",
      },
      {
        name: "Mini Postres Surtidos",
        price: 22.5,
        categorySlug: "postres",
        occasionSlugs: ["felicidades"],
        description: "Bandeja de doce mini postres para compartir.",
      },
      {
        name: "Pastel de Bodas Mini",
        price: 42,
        categorySlug: "pasteles",
        occasionSlugs: ["propuesta"],
        description: "Pastel de dos pisos a escala reducida, ideal para momentos íntimos.",
      },
      {
        name: "Galletas Decoradas con Mensaje",
        price: 16,
        categorySlug: "postres",
        occasionSlugs: ["pense-en-vos"],
        description: "Media docena de galletas decoradas con el mensaje que quieras.",
        personalizable: true,
      },
    ],
  },
  {
    name: "Globos y Fiesta SV",
    municipalitySlug: "soyapango",
    whatsapp: "+503 7000-0005",
    description: "Decoración con globos para fiestas y celebraciones. [DEMO]",
    addressLine: "Ciudad Delgado, Soyapango",
    prepMinutes: 150,
    products: [
      {
        name: "Bouquet de Globos Metálicos",
        price: 19.99,
        categorySlug: "globos",
        occasionSlugs: ["cumpleanos", "felicidades"],
        description: "Seis globos metálicos con helio, listos para entregar.",
      },
      {
        name: "Arco de Globos para Fiesta",
        price: 55,
        compareAtPrice: 65,
        categorySlug: "globos",
        occasionSlugs: ["celebraciones"],
        description: "Arco de globos personalizado por colores para tu evento.",
      },
      {
        name: "Globo Gigante con Mensaje",
        price: 14.5,
        categorySlug: "globos",
        occasionSlugs: ["felicidades"],
        description: "Globo gigante transparente con confeti y mensaje a elección.",
        personalizable: true,
      },
      {
        name: "Kit de Fiesta Sorpresa",
        price: 40,
        categorySlug: "celebraciones",
        occasionSlugs: ["cumpleanos"],
        description: "Globos, banderines y accesorios para una fiesta sorpresa completa.",
      },
      {
        name: "Globos + Confeti Box",
        price: 21,
        categorySlug: "celebraciones",
        occasionSlugs: ["solo-porque-si"],
        description: "Caja sorpresa llena de confeti con globos incluidos.",
      },
      {
        name: "Globo Corazón de Aniversario",
        price: 17.5,
        categorySlug: "globos",
        occasionSlugs: ["aniversario", "te-amo"],
        description: "Globo en forma de corazón, tamaño gigante, con helio.",
      },
    ],
  },
  {
    name: "Peluches Ticos",
    municipalitySlug: "mejicanos",
    whatsapp: "+503 7000-0006",
    description: "Peluches y detalles personalizados. [DEMO]",
    addressLine: "Zacamil, Mejicanos",
    prepMinutes: 90,
    products: [
      {
        name: "Oso de Peluche Gigante",
        price: 29.99,
        compareAtPrice: 36.99,
        categorySlug: "peluches",
        occasionSlugs: ["te-amo", "aniversario"],
        description: "Oso de peluche de 80cm, suave y de alta calidad.",
      },
      {
        name: "Peluche con Camiseta Personalizada",
        price: 24,
        categorySlug: "peluches",
        occasionSlugs: ["pense-en-vos"],
        description: "Peluche mediano con una camiseta bordada con el texto que elijas.",
        personalizable: true,
      },
      {
        name: "Set Peluche + Rosa + Chocolate",
        price: 33.5,
        categorySlug: "peluches",
        occasionSlugs: ["aniversario"],
        description: "Combo clásico: peluche, una rosa y chocolates.",
      },
      {
        name: "Peluche Bebé para Baby Shower",
        price: 19.99,
        categorySlug: "peluches",
        occasionSlugs: ["felicidades"],
        description: "Peluche pequeño ideal para regalos de bienvenida.",
      },
      {
        name: "Llavero Personalizado con Foto",
        price: 9.5,
        categorySlug: "personalizados",
        occasionSlugs: ["pense-en-vos"],
        description: "Llavero acrílico con la foto que nos envíes.",
        personalizable: true,
      },
      {
        name: 'Taza Personalizada "Te Extraño"',
        price: 12.99,
        categorySlug: "personalizados",
        occasionSlugs: ["te-extrano"],
        description: "Taza de cerámica con diseño y mensaje personalizado.",
        personalizable: true,
      },
    ],
  },
  {
    name: "Desayunos Sorpresa SV",
    municipalitySlug: "santa-tecla",
    whatsapp: "+503 7000-0007",
    description: "Desayunos sorpresa a domicilio. [DEMO]",
    addressLine: "Merliot, Santa Tecla",
    prepMinutes: 120,
    products: [
      {
        name: "Desayuno Sorpresa Clásico a Domicilio",
        price: 28,
        categorySlug: "desayunos-sorpresa",
        occasionSlugs: ["cumpleanos", "aniversario"],
        description: "Charola con frutas, pan dulce, jugo y café para sorprender a primera hora.",
      },
      {
        name: "Desayuno Romántico para Dos",
        price: 38,
        categorySlug: "desayunos-sorpresa",
        occasionSlugs: ["aniversario", "te-amo"],
        description: "Desayuno completo para compartir en pareja, con detalle floral incluido.",
      },
      {
        name: "Charola de Frutas y Café",
        price: 22.5,
        categorySlug: "desayunos-sorpresa",
        occasionSlugs: ["gracias"],
        description: "Frutas de temporada y café de especialidad en presentación elegante.",
      },
      {
        name: "Desayuno Saludable Sorpresa",
        price: 26,
        categorySlug: "desayunos-sorpresa",
        occasionSlugs: ["solo-porque-si"],
        description: "Opción balanceada con granola, yogurt y frutas frescas.",
      },
      {
        name: "Desayuno + Globo + Tarjeta",
        price: 34,
        categorySlug: "desayunos-sorpresa",
        occasionSlugs: ["felicidades"],
        description: "Desayuno completo acompañado de un globo y tarjeta personalizada.",
        personalizable: true,
      },
    ],
  },
  {
    name: "Joyería Luna",
    municipalitySlug: "antiguo-cuscatlan",
    whatsapp: "+503 7000-0008",
    description: "Joyería fina para momentos especiales. [DEMO]",
    addressLine: "La Sultana, Antiguo Cuscatlán",
    prepMinutes: 240,
    products: [
      {
        name: "Anillo de Compromiso Clásico",
        price: 250,
        categorySlug: "propuestas",
        occasionSlugs: ["propuesta"],
        description: "Anillo de plata con baño de rodio y piedra central.",
      },
      {
        name: "Collar con Dije Grabado",
        price: 45,
        categorySlug: "propuestas",
        occasionSlugs: ["aniversario", "te-amo"],
        description: "Collar de plata con dije grabado con iniciales o fecha.",
        personalizable: true,
      },
      {
        name: "Pulsera de Plata para Aniversario",
        price: 38,
        categorySlug: "propuestas",
        occasionSlugs: ["aniversario"],
        description: "Pulsera de plata 925 con dije de corazón.",
      },
      {
        name: "Aretes Elegantes",
        price: 32,
        categorySlug: "propuestas",
        occasionSlugs: ["felicidades"],
        description: "Aretes de plata con acabado brillante, presentación en estuche.",
      },
      {
        name: "Caja de Propuesta con Velas y Pétalos",
        price: 65,
        categorySlug: "propuestas",
        occasionSlugs: ["propuesta"],
        description: "Set decorativo para preparar el momento de la propuesta.",
      },
    ],
  },
  {
    name: "Cartas & Detalles",
    municipalitySlug: "san-salvador",
    whatsapp: "+503 7000-0009",
    description: "Cartas y detalles escritos con cariño. [DEMO]",
    addressLine: "Colonia Miramonte, San Salvador",
    prepMinutes: 60,
    products: [
      {
        name: "Carta de Amor Escrita a Mano",
        price: 8.99,
        categorySlug: "cartas",
        occasionSlugs: ["te-amo"],
        description: "Carta caligrafiada a mano con el mensaje que nos compartas.",
        personalizable: true,
      },
      {
        name: "Tarjeta Pop-up Personalizada",
        price: 11.5,
        categorySlug: "cartas",
        occasionSlugs: ["felicidades"],
        description: "Tarjeta 3D pop-up con diseño y mensaje a elección.",
        personalizable: true,
      },
      {
        name: "Set de Cartas para Cada Ocasión",
        price: 19.99,
        categorySlug: "cartas",
        occasionSlugs: ["solo-porque-si"],
        description: "Set de cinco tarjetas ilustradas para distintas ocasiones.",
      },
      {
        name: "Marco de Fotos Personalizado",
        price: 22,
        categorySlug: "personalizados",
        occasionSlugs: ["pense-en-vos"],
        description: "Marco de madera grabado con nombres o fecha especial.",
        personalizable: true,
      },
      {
        name: 'Libreta "Razones por las que te amo"',
        price: 17,
        categorySlug: "cartas",
        occasionSlugs: ["te-amo"],
        description: "Libreta ilustrada para llenar con razones personales.",
        personalizable: true,
      },
    ],
  },
  {
    name: "Todo Regalos SV",
    municipalitySlug: "la-libertad",
    whatsapp: "+503 7000-0010",
    description: "Regalos variados para toda ocasión. [DEMO]",
    addressLine: "Playa El Sunzal, La Libertad",
    prepMinutes: 120,
    products: [
      {
        name: "Combo Flores + Chocolates + Carta",
        price: 42,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["aniversario", "te-amo"],
        description: "El combo completo: flores frescas, chocolates y una carta personalizada.",
        personalizable: true,
      },
      {
        name: "Canasta de Regalo Variada",
        price: 48,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["felicidades"],
        description: "Canasta con snacks, dulces y un detalle sorpresa.",
      },
      {
        name: "Kit Graduación Completo",
        price: 36,
        categorySlug: "celebraciones",
        occasionSlugs: ["graduacion"],
        description: "Globo de graduación, tarjeta y un detalle conmemorativo.",
      },
      {
        name: "Regalo Sorpresa Misterioso",
        price: 30,
        categorySlug: "celebraciones",
        occasionSlugs: ["solo-porque-si"],
        description: "Una selección sorpresa de detalles — vos elegís el presupuesto, nosotros el resto.",
      },
      {
        name: "Combo Día de la Madre",
        price: 39.99,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["dia-de-la-madre"],
        description: "Flores, chocolates y una tarjeta especial para mamá.",
      },
      {
        name: "Combo Día del Padre",
        price: 37.99,
        categorySlug: "cajas-de-regalo",
        occasionSlugs: ["dia-del-padre"],
        description: "Detalles pensados especialmente para papá.",
      },
    ],
  },
];
